# run config
seed:       42
epochs:     500
batch_size: 32 #64
lr:         0.0001
optimizer:  adamw
model_dir:  outputs/models
submit_dir: outputs/submissions
data_dir:   outputs/datasets
device: cuda # cpu

# data config
neg_count:  100
feature_sets: { # feature: [use_flag(1: on, 0: off) , type(C: Categorical, N: Numeric)]
    'user':     [1,C],
    'item':     [1,C],
    'time':     [0,N], # AE confidence ?
    'year':     [0,N],
    'writer':   [0,C],
    'title':    [0,C],
    'genre':    [0,C],
    'director': [0,C],
}
data_rebuild: False # True, False

# model config
model_name: DAE # FM, DeepFM, AE, DAE, VAE, MultiVAE, MultiAE, MultiDAE, MultiVDAE

# FM
emb_dim:    64

# AE
latent_dim: 256
encoder_dims: [1024, 512]
confidence: 'itempop' # time, itempop, gerneprefer

# DAE
dropout:        0.5
noise_factor:   0.3     # only DAE

# VAE
kl_anneal:          False   # True/False
beta_fix:           1.3
anneal_beta_max:    .2      # 아래 조건이 beta_max 에 막힘
anneal_total_steps: 200000  # epoch 100까지 iter 마다 anneal을 증가시켜 1에 도달함

# wandb config
wandb:      True # True, False
project:    movierec

# logging level
log_dir:    logs/
