# run config
seed:       42
epochs:     1 #00
batch_size: 64
lr:         0.001
optimizer:  adamw
model_dir:  outputs/models
submit_dir: outputs/submissions
data_dir:   outputs/datasets

# data config
neg_count:  50
feature_sets: {
    'user':     1,
    'item':     1,
    'title':    0,
}

# model config
model_name: DeepFM
emb_dim:    64

# wandb config
wandb:      True # False
project:    movierec
