# run config
seed:       42
epochs:     100
batch_size: 64
lr:         0.001
optimizer:  adamw
model_dir:  outputs/models
submit_dir: outputs/submissions
data_dir:   outputs/datasets
device: cuda # cpu

# data config
neg_count:  50
feature_sets: { # feature: [use_flag(1: on, 0: off) , type(C: Categorical, N: Numeric)]
    'user':     [1,C],
    'item':     [1,C],
    'time':     [0,N],
    'year':     [1,N],
    'writer':   [0,C],
    'title':    [0,C],
    'genre':    [0,C],
    'director': [0,C],
}
data_rebuild: False # True, False

# model config
model_name: AE # FM, DeepFM, VAE
emb_dim:    64
latent_dim: 256
encoder_dims: [1024, 512]

# wandb config
wandb:      False # True, False
project:    movierec

# logging level
log_dir:    logs/
